# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    # session:
    #     cookie_lifetime: 1800      # Durée de vie du cookie de session en secondes (ici, 30 minutes)
    #     gc_maxlifetime: 1800       # Durée maximale de session côté serveur, en secondes

    #esi: true
    #fragments: true

#    serializer:
#        default_context:
#            circular_reference_limit: 1
#            enable_max_depth: true
#            max_depth: 1

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

